apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: g4vnsf29w-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/g4vnsf29w-java-springboot-gitops